### ISSUE TITLE
Directory Navigation Buttons Removal

### ISSUE THREAD

**Issue by onaib-faisal** [Heath-AFM-Lab/pNanoLocz#13]
Look into how we want to implement the directory navigation. Might not need the down button because of the new tree structure design in pane.

**Comment by DynoAbd786** [comment]
Will try to look into this in the next branch, something probably called "Depth_Control_Functionality"

**Comment by DynoAbd786** [comment]
Discussed with supervisor, requested that we remove these buttons as the file tree structure now suffices
