### ISSUE TITLE
Data/Parameter values missing and/or miscalculated

### ISSUE THREAD

**Issue by DynoAbd786** [Heath-AFM-Lab/pNanoLocz#15]
.ARIS files have either missing or miscalcualted file metadata.
Missing:

- Speed (fps)
- Line/s (Hz)

Possibly miscalculated:
- pixel/nm scaling

it is not known whether this is consistent with other file formats. Comparison with NanoLocz is given below

![image](https://github.com/user-attachments/assets/0b98f179-2f45-4dc2-b324-cf26dae1239f)
![image](https://github.com/user-attachments/assets/11f57f08-ed84-4781-b370-d12b766fffca)

**Comment by onaib-faisal** [comment]
Fixed with correct calculations
